#!/usr/bin/env python3
# Contact a Bosh-Siemens Home Connect device
# todo: document how to extract the psk
import sys
import json
import re
import time
import io
from HCSocket import HCSocket, now
from HCDevice import HCDevice

if True:
	# clothes dryer
	#  RX:{'service': 'ro', 'version': 1}
	#  {'service': 'ei', 'version': 2}
	#  {'service': 'ci', 'version': 2}
	#  {'service': 'ni', 'version': 1}]}
	host = '10.1.0.145'
	psk64 = 'KlRQQyG8AkEfRFPr0v7vultz96zcal5lxj2fAc2ohaY'
	iv64 = 'tTUvqcsBldtkhHvDwE2DpQ'
else:
	# dish washer
	# RX: {"service":"ci","version":3}
	# {"service":"ei","version":2}
	# {"service":"iz","version":1}
	# {"service":"ni","version":1}
	# {"service":"ro","version":1}]}
	host = "10.1.0.133"
	psk64 = "Dsgf2MZJ-ti85_00M1QT1HP5LgH82CaASYlMGdcuzcs="
	iv64 = None # no iv == https

ws = HCSocket(host, psk64, iv64)
dev = HCDevice(ws)

while True:
	try:
		buf = dev.recv()
	except Exception as e:
		print("error handling msg", e, buf)
		time.sleep(5)
		ws.reconnect()
